name: Deploy AKS-Construction

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  reusable_workflow_job:
    uses: Azure/AKS-Construction/.github/workflows/AKSC_Deploy.yml@0.10.3
    with:
      templateVersion: 0.10.3
      rg: appdemogroup2
      resourceName: appdemo2
      templateParams: resourceName=appdemo2 agentCount=1 JustUseSystemPool=true osDiskType=Managed osDiskSizeGB=32 custom_vnet=true CreateNetworkSecurityGroups=true registries_sku=Basic acrPushRolePrincipalId=_USER_OBJECT_ID_ automationAccountScheduledStartStop=Weekday
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      USER_OBJECT_ID: ${{ secrets.USER_OBJECT_ID }}
